app:
  name: "bluebell"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "bluebell.log"
  maxSize: 200
  maxAge: 30
  maxBackups: 7

mysql:
  host: "192.168.0.110"
  port: 3306
  user: "root"
  password: "123456"
  dbName: "bluebell"

redis:
  host: "192.168.0.110"
  port: 6379
  db: 0